windows tests: forgot some EXEEXT's
which fixes i.e. mingw32 cross tests on linux.

diff --git a/programs/alive.test.in b/programs/alive.test.in
--- a/programs/alive.test.in
+++ b/programs/alive.test.in
@@ -38,6 +38,7 @@ top_builddir="@top_builddir@"
 CFLAGS="@CFLAGS@"
 DISABLE_JSON="@DISABLE_JSON@"
 DISABLE_WRITE="@DISABLE_WRITE@"
+EXEEXT="@EXEEXT@"
 
 i=0
 rm -f ./*-dxf*.log ./*-read,.log ./*-write.log ./*-json.log ./*-rw.log
@@ -166,7 +167,7 @@ run ()
     #then
     #   TESTPROG="env ASAN_OPTIONS=detect_leaks=0 $TESTPROG"
     #fi
-    echo "$TESTPROG ./$prog $arg 2>$log"
+    echo "$TESTPROG $prog $arg 2>$log"
     # writers can hang
     #if test $bprog = dwgrewrite -o $bprog = dwgwrite -o $bprog = dxf2dwg
     #then
@@ -250,20 +251,20 @@ if false; then
 for prog in dwgwrite dwgrewrite dxf2dwg dwg2dxf dxfwrite ; do
     for dwg in $DATA; do
         for as in --as=r13 --as=r2000 --as=r2004 --as=r2010 --as=r2013 --as=r2018; do
-            run "$prog" "$dwg" "$as"
+            run "$prog${EXEEXT}" "$dwg" "$as"
         done
     done
 done
 fi
 
 case $PROGS in
-  *dwggrep*)
-    echo "@LTEXEC@ ./dwggrep -i -c tekst ${DATADIR}/example_*.dwg"
-    if test "$(@LTEXEC@ ./dwggrep -i -c tekst "${DATADIR}"/example_*.dwg)" != "24"; then
-      i=$((i+1))
-      echo "dwggrep failure $?"
-    fi
-
+    *dwggrep*)
+        echo "@LTEXEC@ dwggrep${EXEEXT} -i -c tekst ${DATADIR}/example_*.dwg"
+        n=$(@LTEXEC@ ./dwggrep${EXEEXT} -i -c tekst "${DATADIR}"/example_*.dwg)
+        if test "$n" != "24"; then
+            i=$((i+1))
+            echo "dwggrep failure $?, result $n, expected 24"
+        fi
 esac
 
 #run dwgread r11/ACEL10
@@ -274,7 +275,7 @@ esac
 # only in programs, not examples:
 if [ -f cmp_dxf.pl ] && [ -e dwg2dxf ]; then
     for dwg in $DATA; do
-        run dwg2dxf "$dwg"
+        run dwg2dxf${EXEEXT} "$dwg"
         #if [ -f ${DATADIR}/$dwg.dxf ]; then
         #    base="$(basename "$dwg" .dwg)"
         #    perl filt_dxf.pl ${DATADIR}/$dwg.dxf > $base.dxf.orig
