alive.test: dwggrep -c now returns 21
The block_header iterator get_next_owned_entity finds now more.

diff --git a/programs/alive.test.in b/programs/alive.test.in
--- a/programs/alive.test.in
+++ b/programs/alive.test.in
@@ -25,8 +25,7 @@
 # file whose name is DWG-PROG.log.
 #
 # If there are no problems, exit successfully.  Otherwise display
-# the count of problem runs, the list of *.log files and finally
-# exit failurefully.
+# the count of problem runs, the list of *.log files and exit with failure.
 # datadir must be set to support testing from a separate build dir.
 
 # Code:
@@ -35,7 +34,7 @@ test "$PROGS" || { echo ERROR: Env var PROGS not set ; exit 1 ; }
 test "$datadir" || { echo ERROR: Env var datadir not set ; exit 1 ; }
 
 problems=0
-rm -f dwg*.log
+rm -f *dwg*.log
 
 #just check that it does not crash
 run ()
@@ -47,6 +46,7 @@ run ()
     bdwg=`basename $dwg .dwg`
     log=$bdwg-$bprog.log
     arg="${datadir}/$dwg.dwg"
+    rm $log 2>/dev/null
     case $bprog in
     dwglayers)  ;;
     dwggrep)    arg="-i tekst $arg" ;;
@@ -83,6 +83,7 @@ run ()
                 echo $(basename $0): TODO $prog $tmpnum failures
                 ls -l $log ;;
         *)      problems=$(expr 1 + $problems)
+                echo $prog failure $?
                 tail -n100 $log ;;
         esac
     fi
@@ -112,9 +113,10 @@ done
 case $PROGS in
   *dwggrep*)
     top_builddir=..
-    echo ../libtool --mode=execute ./dwggrep -i -c tekst ${datadir}/example_*.dwg
-    if test x"`@LTEXEC@ ./dwggrep -i -c tekst ${datadir}/example_*.dwg`" != x"16"; then
+    echo @LTEXEC@ ./dwggrep -i -c tekst ${datadir}/example_*.dwg
+    if test x"`@LTEXEC@ ./dwggrep -i -c tekst ${datadir}/example_*.dwg`" != x"21"; then
       problems=$(expr 1 + $problems)
+      echo dwggrep failure $?
     fi
 
 esac
