dxf.test: stricter check_roundtrip

diff --git a/programs/dxf.test.in b/programs/dxf.test.in
--- a/programs/dxf.test.in
+++ b/programs/dxf.test.in
@@ -15,6 +15,13 @@
 [ -z "$DATADIR" ] && DATADIR="@top_srcdir@/test/test-data"
 top_builddir="@top_builddir@"
 EXEEXT="@EXEEXT@"
+# shellcheck disable=SC2157
+if [ -n "@HAVE_ASAN@" ]
+then
+    DXF2DWG="env ASAN_OPTIONS=detect_leaks=0 @LTEXEC@ ./dxf2dwg${EXEEXT}"
+else    
+    DXF2DWG="@LTEXEC@ ./dxf2dwg${EXEEXT}"
+fi
 # artefact for "shellcheck"
 [ -z "$top_builddir" ] && echo $top_builddir
 
@@ -171,9 +178,18 @@ check_roundtrip() {
         tgt="$(basename "$dwg")"
         log1="$(basename "$dwg" .dwg).log1"
         log2="$(basename "$dwg" .dwg).log2"
-        @LTEXEC@ "./dwg2dxf${EXEEXT}" -y -v2 -o "$dxf" "$dwg" 2>"$log1" >/dev/null
-        @LTEXEC@ "./dxf2dwg${EXEEXT}" -y -v0 -o "$tgt" "$dxf" 2>/dev/null >/dev/null
-        @LTEXEC@ "./dwgread${EXEEXT}" -v2 "$tgt" 2>"$log2" >/dev/null
+        if ! @LTEXEC@ "./dwg2dxf${EXEEXT}" -y -v2 -o "$dxf" "$dwg" 2>"$log1" >/dev/null; then
+            echo "dwg2dxf $dwg failed"
+            exit 1
+        fi
+        if ! $DXF2DWG -y -v0 -o "$tgt" "$dxf" 2>/dev/null >/dev/null; then
+            echo "$DXF2DWG -y -v0 -o $tgt $dxf failed"
+            exit 1
+        fi
+        if ! @LTEXEC@ "./dwgread${EXEEXT}" -v2 "$tgt" 2>"$log2" >/dev/null; then
+            echo "dwgread $tgt failed"
+            exit 1
+        fi
         # We dont write unstable entities yet. WIPEOUT is converted to POINT in encode, but skipped at out_dxf
         if [ -n "$enable_debug" ] && [ -z "$is_release" ]; then
             expect="$(grep -E '^Add entity' "$log1" | grep -E -c -v 'entity (WIPEOUT|UNKNOWN_ENT)')"
